name: qi_diet_dna_calculus
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - bioconda::kraken2=2.0.8_beta
  - bioconda::adapterremoval=2.3.0
  - bioconda::fastx_toolkit=0.0.14
  - bioconda::vsearch=1.1.3
  - bioconda::cutadapt=1.9.1
  - bioconda::gargammel=1.1.2
  - bioconda::nextflow=20.04.1
  - bioconda::bowtie2=2.4.2
  - bioconda::mapdamage2=2.0.6
