---
title: "QI Dietary Analysis - Minimum Reads for Damage"
output: html_notebook
---

Load Libraries

```{r}
library(readr)
library(tidyr)
library(purrr)
library(magrittr)
library(tibble)
library(dplyr)
library(ggplot2)
library(stringr)
```

Load files

```{r}
data <- Sys.glob("~/projects1/users/fellows/diet_calculus/analysis/min_reads_damage/*/downsampling/damageprofiles/*/*") %>%
  list.files("5p_freq_misincorporations.txt", full.names = T) %>%
  enframe(name = NULL, value = "file") %>%
  mutate(contents = map(file, ~read_tsv(.x, comment = '#', col_types = "idddddddddddddd"))) %>%
  mutate(reads = map(file, ~str_extract(.x, "rmdup-\\d*(?:reads)") %>% gsub("rmdup-|reads", "", .)) %>% unlist %>% as.integer()) %>% 
  mutate(reference = map(file, ~str_extract(.x, "reads/(.*)_null") %>% gsub("reads/|_null", "", .)) %>% unlist) %>% 
  select(reference, reads, contents) %>%
  unnest(contents)

data <- data %>%
  rename(insertion = `->ACGT`, deletion = `ACGT>-`, Position = Pos) %>%
  pivot_longer(contains(c(">", "insertion", "deletion")), names_to = "Mutation Type", values_to = "Frequency")
  
```

Now we can plot!

```{r}
## Colours
type_colours <- c("C>T" = "red", "G>A" = "blue", "A>C" = "grey", "A>G" = "grey", "A>T" = "grey", "C>A" = "grey", "C>G" = "grey", "G>C" = "grey", "G>T" = "grey", "T>A" = "grey", "T>C" = "grey",	"T>G" = "grey", "insertion" = "purple", "deletion" = "green")

## Linean name formaT!
# make_linean <- function(x){
#   string <- 
# }

## TODO SAVE data!

## Clean up some stuff for pretty plotting
data <- data %>% 
  mutate(`Mutation Type` = factor(`Mutation Type`, levels = rev(names(type_colours)))) %>%
  mutate()

ggplot(data %>% filter(reads > 50), aes(Position, Frequency, colour = `Mutation Type`)) +
  geom_line() +
  theme_bw() +
  ylim(0, 0.30) +
  scale_colour_manual(values = type_colours, guide = guide_legend(reverse = TRUE)) +
  facet_grid(reference ~ reads)
```


